data = pd.DataFrame(
    np.concatenate(
        [
            current_measured,
            voltage_measured,
            current_load,
            voltage_load,
            temperature_measured,
            time,
        ]
    ).T,
    columns=[
        "current_measured",
        "voltage_measured",
        "current_load",
        "voltage_load",
        "temperature_measured",
        "time",
    ],
)
num_samples = len(data)
cycle_data.append(
    [
        "discharge",
        int(battery_id[1::]),
        cycle_discharge_id,
        time_cycle_start,
        ambient_temperature,
        data,
        num_samples,
        capacity_k_Ahr,
    ]
)